_HEADER_COMMENT = "// This file was generated by img2gb, DO NOT EDIT\n\n"


def tileset_to_c(tileset, name="tileset"):
    c = _HEADER_COMMENT
    c += "const UINT8 %s[] = {\n" % name.upper()
    for tile in tileset.tiles:
        c += "    %s,\n" % ", ".join(["0x%02X" % b for b in tile.data])
    c += "};\n"
    return c


def tileset_to_h(tileset, name="tileset"):
    h = _HEADER_COMMENT
    h += "#ifndef _%s_H\n" % name.upper()
    h += "#define _%s_H\n\n" % name.upper()
    h += "const UINT8 %s[];\n" % name.upper()
    h += "const UINT8 %s_TILE_COUNT = %i;\n" % (name.upper(), tileset.length)
    h += "\n#endif\n"
    return h
